export const airportList = [
  {
    iataCode: "BSB",
    airportName: "Aeroporto Internacional Presidente Jucelino Kubitschek",
    airportCity: "Brasília",
    airportUF: "Distrito Federal",
  },
  {
    iataCode: "CGH",
    airportName: "Aeroporto Internacional de São Paulo Congonhas",
    airportCity: "São Paulo",
    airportUF: "São Paulo",
  },
  {
    iataCode: "GIG",
    airportName: "Aeroporto Internacional Galeão Antônio Carlos Jobim",
    airportCity: "Janeiro",
    airportUF: "Rio de Janeiro",
  },
  {
    iataCode: "SSA",
    airportName: "Aeroporto Internacional Deputado Luis Eduardo Magalhães",
    airportCity: "Salvador",
    airportUF: "Bahia",
  },
  {
    iataCode: "FLN",
    airportName: "Aeroporto Internacional Hercílio Luz",
    airportCity: "Florianópolis",
    airportUF: "Santa Catarina",
  },
  {
    iataCode: "POA",
    airportName: "Aeroporto Internacional Salgado Filho",
    airportCity: "Porto Alegre",
    airportUF: "Rio Grande do Sul",
  },
  {
    iataCode: "VCP",
    airportName: "Aeroporto Internacional de Viracopos, Campinas",
    airportCity: "Campinas",
    airportUF: "São Paulo",
  },
  {
    iataCode: "REC",
    airportName: "Aeroporto Internacional Guararapes – Gilberto Freyre",
    airportCity: "Recife",
    airportUF: "Pernambuco",
  },
  {
    iataCode: "CWB",
    airportName: "Aeroporto Internacional Afonso Pena",
    airportCity: "Curitiba",
    airportUF: "Paraná",
  },
  {
    iataCode: "BEL",
    airportName: "Aeroporto Internacional Val de Cans",
    airportCity: "Belém",
    airportUF: "Pará",
  },
  {
    iataCode: "VIX",
    airportName: "Aeroporto de Vitória – Eurico de Aguiar Salles",
    airportCity: "Vitória",
    airportUF: "Espírito Santo",
  },
  {
    iataCode: "SDU",
    airportName: "Aeroporto Santos Dumont",
    airportCity: "Santos Dumont",
    airportUF: "Rio de Janeiro",
  },
  {
    iataCode: "CGB",
    airportName: "Aeroporto Internacional Marechal Rondon",
    airportCity: "Cuiabá",
    airportUF: "Mato Grosso",
  },
  {
    iataCode: "CGR",
    airportName: "Aeroporto Internacional de Campo Grande",
    airportCity: "Campo Grande",
    airportUF: "Mato Grosso do Sul",
  },
  {
    iataCode: "FOR",
    airportName: "Aeroporto Internacional Pinto Martins",
    airportCity: "Fortaleza",
    airportUF: "Ceará",
  },
  {
    iataCode: "MCP",
    airportName: "Aeroporto Internacional de Macapá",
    airportCity: "Macapá",
    airportUF: "Amapá",
  },
  {
    iataCode: "MGF",
    airportName: "Aeroporto Regional Silvio Name Junior",
    airportCity: "Maringá",
    airportUF: "Paraná",
  },
  {
    iataCode: "GYN",
    airportName: "Aeroporto de Goiânia, Santa Genoveva",
    airportCity: "Goiânia",
    airportUF: "Goiânia",
  },
  {
    iataCode: "NVT",
    airportName:
      "Aeroporto Internacional de Navegantes, Ministro Victor Konder",
    airportCity: "Navegantes",
    airportUF: "Santa Catarina",
  },
  {
    iataCode: "MAO",
    airportName: "Aeroporto Internacional de Manaus, Eduardo Gomes",
    airportCity: "Manaus",
    airportUF: "Amazonas",
  },
  {
    iataCode: "NAT",
    airportName: "Aeroporto Internacional de Natal, Augusto Severo",
    airportCity: "Natal",
    airportUF: "Rio Grande do Norte",
  },
  {
    iataCode: "BPS",
    airportName: "Aeroporto Internacional de Porto Seguro",
    airportCity: "Porto Seguro",
    airportUF: "Bahia",
  },
  {
    iataCode: "MCZ",
    airportName: "Aeroporto de Maceió, Zumbi dos Palmares",
    airportCity: "Maceió",
    airportUF: "Alagoas",
  },
  {
    iataCode: "PMW",
    airportName: "Aeroporto de Palmas/Brigadeiro Lysias Rodrigues",
    airportCity: "Palmas",
    airportUF: "Tocantins",
  },
  {
    iataCode: "SLZ",
    airportName: "Aeroporto Internacional de São Luís, Marechal Cunha Machado",
    airportCity: "São Luis",
    airportUF: "Maranhão",
  },
  {
    iataCode: "GRU",
    airportName:
      "Aeroporto Internacional de Guarulhos-Governador André Franco Motoro",
    airportCity: "Guarulhos",
    airportUF: "São Paulo",
  },
  {
    iataCode: "LDB",
    airportName: "Aeroporto de Governador José Richa",
    airportCity: "Londrina",
    airportUF: "Paraná",
  },
  {
    iataCode: "PVH",
    airportName:
      "Aeroporto Internacional Governador Jorge Teixeira de Oliveira",
    airportCity: "Porto Velho",
    airportUF: "Rondônia",
  },
  {
    iataCode: "RBR",
    airportName: "Aeroporto Internacional Plácido de Castro",
    airportCity: "Rio Branco",
    airportUF: "Acre",
  },
  {
    iataCode: "JOI",
    airportName: "Aeroporto de Joinville, Lauro Carneiro de Loyola",
    airportCity: "Joinville",
    airportUF: "Santa Catarina",
  },
  {
    iataCode: "UDI",
    airportName: "Aeroporto de Uberlândia, Ten. Cel. Av. César Bombonato",
    airportCity: "Uberlândia",
    airportUF: "Minas Gerais",
  },
  {
    iataCode: "CXJ",
    airportName: "Aeroporto Regional de Caxias do Sul, Hugo Cantergiani",
    airportCity: "Caxias do Sul",
    airportUF: "Rio Grande do Sul",
  },
  {
    iataCode: "IGU",
    airportName: "Aeroporto Internacional de Foz do Iguaçu",
    airportCity: "Foz do Iguaçu",
    airportUF: "Paraná",
  },
  {
    iataCode: "THE",
    airportName: "Aeroporto de Teresina – Senador Petrônio Portella",
    airportCity: "Teresina",
    airportUF: "Piauí",
  },
  {
    iataCode: "AJU",
    airportName: "Aeroporto Internacional Santa Maria",
    airportCity: "Aracaju",
    airportUF: "Sergipe",
  },
  {
    iataCode: "JPA",
    airportName: "Aeroporto Internacional Presidente Castro Pinto",
    airportCity: "João Pessoa",
    airportUF: "Paraiba",
  },
  {
    iataCode: "PNZ",
    airportName: "Aeroporto de Petrolina, Senador Nilo Coelho",
    airportCity: "Petrolina",
    airportUF: "Pernambuco",
  },
  {
    iataCode: "CNF",
    airportName: "Aeroporto Internacional de Confins – Tancredo Neves",
    airportCity: "Confins",
    airportUF: "Minas Gerais",
  },
  {
    iataCode: "BVB",
    airportName: "Aeroporto Internacional Atlas Brasil Cantanhede",
    airportCity: "Boa Vista",
    airportUF: "Rondônia",
  },
  {
    iataCode: "CPV",
    airportName: "Aeroporto de Campina Grande, Presidente João Suassuna",
    airportCity: "Campina Grande",
    airportUF: "Paraíba",
  },
  {
    iataCode: "STM",
    airportName: "Aeroporto de Santarém, Maestro Wilson Fonseca",
    airportCity: "Santarém",
    airportUF: "Pará",
  },
  {
    iataCode: "IOS",
    airportName: "Aeroporto de Ilhéus/Bahia-Jorge Amado",
    airportCity: "Ilhéus",
    airportUF: "Bahia",
  },
  {
    iataCode: "JDO",
    airportName: "Aeroporto de Juazeiro do Norte – Orlando Bezerra",
    airportCity: "Juazeiro do Norte",
    airportUF: "Ceará",
  },
  {
    iataCode: "IMP",
    airportName: "Aeroporto de Imperatriz – Prefeito Renato Moreira",
    airportCity: "Imperatriz",
    airportUF: "Maranhão",
  },
  {
    iataCode: "XAP",
    airportName: "Aeroporto de Chapecó – Serafin Enoss Bertaso",
    airportCity: "Chapecó",
    airportUF: "Santa Catarina",
  },
  {
    iataCode: "MAB",
    airportName: "Aeroporto de Marabá",
    airportCity: "Marabá",
    airportUF: "Pará",
  },
  {
    iataCode: "CZS",
    airportName: "Aeroporto Internacional de Cruzeiro do Sul",
    airportCity: "Cruzeiro do Sul",
    airportUF: "Acre",
  },
  {
    iataCode: "PPB",
    airportName: "Aeroporto Estadual de Presidente Prudente",
    airportCity: "Presidente Prudente",
    airportUF: "São Paulo",
  },
  {
    iataCode: "CFB",
    airportName: "Aeroporto Internacional de Cabo Frio",
    airportCity: "Cabo Frio",
    airportUF: "Rio de Janeiro",
  },
  {
    iataCode: "FEN",
    airportName: "Aeroporto de Fernando de Noronha",
    airportCity: "Fernando de Noronha",
    airportUF: "Pernambuco",
  },
  {
    iataCode: "JTC",
    airportName: "Aeroporto Estadual de Bauru/Arealva",
    airportCity: "Bauru",
    airportUF: "Sãp Paulo",
  },
  {
    iataCode: "MOC",
    airportName: "Aeroporto de Montes Claros/Mário Ribeiro",
    airportCity: "Montes Claros",
    airportUF: "Minas Gerais",
  },
  {
    iataCode: "MIA",
    airportName: "Miami International Airport",
    airportCity: "Miami",
    airportUF: "FLorida",
  },
];
